### PR TITLE
damn looking

### PR DESCRIPTION
**Pull request by LieuMai**
- package.json: add react icon
- app.css: header color
- textbox.css: styling search bar
- textbox.js: reactdom for render data, add search icon
- index.css: root style, display style, bonus darkmode style

### CODE REVIEW

**Review by garg-madhur-garg — CHANGES_REQUESTED** [review]
image

I like UI very much ✨
But I want 1 change (if you can do)🤔
Can you do something so that the Key and its value do not display in the same box?

@LieuMai

**Comment by LieuMai** [comment]
You mean bio, location and public repo will be split-out from there value, right? 😄  I will change it but can you describe more detail how you want to change it.

**Comment by garg-madhur-garg** [comment]
> 
> 
> You mean bio, location and public repo will be split-out from there value, right? 😄 I will change it but can you describe more detail how you want to change it.

image

If you want then you can make this page responsive.
And I think instead of splitting you can Capitalize the letters😊

And any other suggestions are always welcome !!
@LieuMai

**Review by garg-madhur-garg — COMMENTED** [review]
You can continue your work

**Comment by LieuMai** [comment]
Thank you for your comment! I make a little bit change but responsive need more time. Don't worry, I will comeback.
image

**Comment by garg-madhur-garg** [comment]
Looking Good ✨
@LieuMai

**Pull request merged**
